name: Build with clang and run

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

env:
  CC: clang

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install X11 dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-dev libxrandr-dev libxi-dev libxinerama-dev libxcursor-dev
      
    - name: Build
      run: make test
